# НАРУШЕНИЕ: hostPath volume — нарушает PodSecurity restricted/baseline
# Ожидается: forbidden: violates PodSecurity "restricted:latest"
apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
  labels:
    app: insecure-demo
    violation: hostpath-volume
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: host-volume
          mountPath: /host-data
  volumes:
    - name: host-volume
      hostPath:
        path: /var/log
        type: Directory
