# НАРУШЕНИЕ: runAsUser: 0 + allowPrivilegeEscalation: true — нарушает PodSecurity restricted
# Ожидается: forbidden: violates PodSecurity "restricted:latest"
apiVersion: v1
kind: Pod
metadata:
  name: pod-root-user
  namespace: audit-zone
  labels:
    app: insecure-demo
    violation: root-user
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
