# Namespace audit-zone — PodSecurity: restricted (enforce + audit + warn)
apiVersion: v1
kind: Namespace
metadata:
  name: audit-zone
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    environment: security-audit
    managed-by: propdevelopment-security
  annotations:
    description: "Namespace для аудита безопасности подов. Уровень PodSecurity: restricted."
